export enum EducationType {
    TECHNICAL_COURSE = 'TECHNICAL_COURSE',
    GRADUATION = 'GRADUATION',
    POSTGRADUATION = 'POSTGRADUATION',
    MASTER = 'MASTER',
    DOCTORATE = 'DOCTORATE',
    SECONDARY = 'SECONDARY',
}