export enum ExperienceTime {
  LESS_THAN_ONE_YEAR = 'LESS_THAN_ONE_YEAR',
  ONE_TO_THREE_YEARS = 'ONE_TO_THREE_YEARS',
  THREE_TO_FIVE_YEARS = 'THREE_TO_FIVE_YEARS',
  FIVE_TO_TEN_YEARS = 'FIVE_TO_TEN_YEARS',
  MORE_THAN_TEN_YEARS = 'MORE_THAN_TEN_YEARS',
}
